name: Main


on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
    paths:
      - md-website/**
      - .github/workflows/main.yml

env:
  IMAGE_CACHE_NAME: us-central1-docker.pkg.dev/still-tower-474715-c6/markdown-converter/md-website:build-cache

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: md-website

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: ">=0.14.0"
          args: "--version"

      - name: Lint
        run: ruff check

      - name: Format
        run: ruff format --check
      
  build-docker-image:
    name: Build md-website Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: auth
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}
          token_format: access_token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: ./md-website
          cache-from: type=registry,ref=${{ env.IMAGE_CACHE_NAME }}
          cache-to: type=registry,ref=${{ env.IMAGE_CACHE_NAME }}
